=== raml-apis/Mandrill/schemas/messages_send-raw.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "object",
  "properties": {
    "key": {
      "required": false,
      "type": "string"
    },
    "raw_message": {
      "required": false,
      "type": "string"
    },
    "from_email": {
      "required": false,
      "type": "string"
    },
    "from_name": {
      "required": false,
      "type": "string"
    },
    "to": {
      "required": false,
      "type": "array",
      "items": {
        "required": false,
        "type": "string"
      }
    },
    "async": {
      "required": false,
      "type": "boolean"
    },
    "ip_pool": {
      "required": false,
      "type": "string"
    },
    "send_at": {
      "required": false,
      "type": "string"
    },
    "return_path_domain": {
      "required": false,
      "type": "null"
    }
  }
}

=== raml-apis/Mandrill/examples/messages_send-raw.json
{
  "key": "example key",
  "raw_message": "From: sender@example.comTo: recipient.email@example.comSubject: Some SubjectSome content.",
  "from_email": "sender@example.com",
  "from_name": "From Name",
  "to": [
    "recipient.email@example.com"
  ],
  "async": false,
  "ip_pool": "Main Pool",
  "send_at": "example send_at",
  "return_path_domain": null
}
